name: publish
on: [push]
jobs:
  publish-wol_bridge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the image
        run: |
          docker build . --tag ghcr.io/n1ght-hunter/wol_bridge:nightly
          docker push ghcr.io/n1ght-hunter/wol_bridge:nightly
